"""Rename prospect_id to future_prospect_id

Revision ID: 7b6f7337593d
Revises: e3fd1167763d
Create Date: 2024-06-15 16:13:47.472232

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b6f7337593d'
down_revision = 'e3fd1167763d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('major_prospect', 'prospect_id', new_column_name='future_prospect_id', existing_type=sa.Integer(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('major_prospect', 'future_prospect_id', new_column_name='prospect_id', existing_type=sa.Integer(), existing_nullable=True)
    # ### end Alembic commands ###
