"""Add major_level to college_detail

Revision ID: 971ab6244eff
Revises: 7b6f7337593d
Create Date: 2024-06-17 05:31:05.213915

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '971ab6244eff'
down_revision = '7b6f7337593d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('major', 'weight')
    # add major_level to college_detail
    op.add_column('college_detail', sa.Column('major_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('major', sa.Column('weight', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # remove major_level from college_detail
    op.drop_column('college_detail', 'major_level')
    # ### end Alembic commands ###
