"""Modul college

Revision ID: e29bd299cebe
Revises: b9629505f9b3
Create Date: 2024-05-30 21:53:33.732066

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e29bd299cebe'
down_revision = 'b9629505f9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    college_table = op.create_table('college',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('college_type_name', sa.String(length=255), nullable=True),
    sa.Column('college_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    major_table = op.create_table('major',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('major_name', sa.String(length=255), nullable=True),
    sa.Column('major_definition', sa.Text(), nullable=True),
    sa.Column('major_image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    course_table = op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('course_name', sa.String(length=255), nullable=True),
    sa.Column('course_image', sa.Text(), nullable=True),
    sa.Column('course_definition', sa.Text(), nullable=True),
    sa.Column('course_explain', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    personality_table = op.create_table('personality',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('personality_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    future_prospect_table = op.create_table('future_prospect',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('future_prospect_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    college_detail_table = op.create_table('college_detail',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('college_id', sa.Integer(), sa.ForeignKey('college.id'), nullable=False),
    sa.Column('major_id', sa.Integer(), sa.ForeignKey('major.id'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    major_personality_table = op.create_table('major_personality',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('major_id', sa.Integer(), sa.ForeignKey('major.id'), nullable=False),
    sa.Column('personality_id', sa.Integer(), sa.ForeignKey('personality.id'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    major_prospect_table = op.create_table('major_prospect',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('major_id', sa.Integer(), sa.ForeignKey('major.id'), nullable=False),
    sa.Column('prospect_id', sa.Integer(), sa.ForeignKey('future_prospect.id'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    major_course_table = op.create_table('major_course',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('major_id', sa.Integer(), sa.ForeignKey('major.id'), nullable=False),
    sa.Column('course_id', sa.Integer(), sa.ForeignKey('course.id'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(college_table,
                   [
                       {'id': 1, 'college_type_name': 'Public University', 'college_name': 'Tech University'},
                       {'id': 2, 'college_type_name': 'Private College', 'college_name': 'Liberal Arts College'}
                   ])

    # Insert dummy data for 'major'
    op.bulk_insert(major_table,
                   [
                       {'id': 1, 'major_name': 'Computer Science', 'major_definition': 'Study of computers and computational systems.', 'major_image': 'url_to_image'},
                       {'id': 2, 'major_name': 'Business Administration', 'major_definition': 'Study of business management.', 'major_image': 'url_to_image'}
                   ])

    # Insert dummy data for 'course'
    op.bulk_insert(course_table,
                   [
                       {'id': 1, 'course_name': 'Introduction to Programming', 'course_image': 'url_to_image', 'course_definition': 'Basic programming concepts.', 'course_explain': 'Detailed explanation of the course.'},
                       {'id': 2, 'course_name': 'Principles of Management', 'course_image': 'url_to_image', 'course_definition': 'Fundamentals of management.', 'course_explain': 'Detailed explanation of the course.'}
                   ])

    # Insert dummy data for 'personality'
    op.bulk_insert(personality_table,
                   [
                       {'id': 1, 'personality_name': 'Analytical'},
                       {'id': 2, 'personality_name': 'Creative'}
                   ])

    # Insert dummy data for 'future_prospect'
    op.bulk_insert(future_prospect_table,
                   [
                       {'id': 1, 'future_prospect_name': 'Software Developer', 'description': 'Develops computer software.'},
                       {'id': 2, 'future_prospect_name': 'Project Manager', 'description': 'Manages projects within an organization.'}
                   ])

    # Insert dummy data for 'college_detail'
    op.bulk_insert(college_detail_table,
                   [
                       {'id': 1, 'college_id': 1, 'major_id': 1},
                       {'id': 2, 'college_id': 2, 'major_id': 2}
                   ])

    # Insert dummy data for 'major_personality'
    op.bulk_insert(major_personality_table,
                   [
                       {'id': 1, 'major_id': 1, 'personality_id': 1},
                       {'id': 2, 'major_id': 2, 'personality_id': 2}
                   ])

    # Insert dummy data for 'major_prospect'
    op.bulk_insert(major_prospect_table,
                   [
                       {'id': 1, 'major_id': 1, 'prospect_id': 1},
                       {'id': 2, 'major_id': 2, 'prospect_id': 2}
                   ])

    # Insert dummy data for 'major_course'
    op.bulk_insert(major_course_table,
                   [
                       {'id': 1, 'major_id': 1, 'course_id': 1},
                       {'id': 2, 'major_id': 2, 'course_id': 2}
                   ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_table('major_course')
    op.drop_table('major_prospect')
    op.drop_table('major_personality')
    op.drop_table('future_prospect')
    op.drop_table('personality')
    op.drop_table('course')
    op.drop_table('major')
    op.drop_table('college_detail')
    op.drop_table('college')
    # ### end Alembic commands ###
