"""Add weight to major

Revision ID: faaac2c77696
Revises: 4f7c4401127f
Create Date: 2024-06-14 01:44:32.559729

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'faaac2c77696'
down_revision = '4f7c4401127f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # add column weight (data type json ) postgresql to major table
    # op.add_column('major', sa.Column('weight', sqlmodel.sql.sqltypes.JSON, nullable=True))
    op.add_column('major', sa.Column('weight', sa.JSON, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # drop column weight from major table
    op.drop_column('major', 'weight')
    # ### end Alembic commands ###
